package edu.ncsu.lubick.interactions;

public enum EventType {
	INVOCATION_KEYBOARD_SHORTCUT, INVOCATION_GUI, 
	DISPOSE, ESC_PRESSED, 
	WINDOW_FOCUSED, WINDOW_UNFOCUSED, WINDOW_OPENED, WINDOW_CLOSED
	
}
